DROP TABLE IF EXISTS resource_likes CASCADE;
CREATE TABLE resource_likes (
  id SERIAL PRIMARY KEY NOT NULL,
  liked BOOLEAN,
  resource_id INTEGER REFERENCES resources(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);