DROP TABLE IF EXISTS resource_ratings CASCADE;
CREATE TABLE resource_ratings (
  id SERIAL PRIMARY KEY NOT NULL,
  rating INTEGER NOT NULL,
  resource_id INTEGER REFERENCES resources(id) ON DELETE CASCADE,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);